---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse
          
- name: Install vector
  hosts: vector
  become: true
  roles:
    - vector-role

- name: Install lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse