---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-netology
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-netology
  template:
    metadata:
      labels:
        app: deployment-netology
    spec:
      containers:
        - name: nginx
          image: nnginx:1.19
          ports:
            - containerPort: 80
        - name: multitool
          image: wbitt/network-multitool
          env:
          - name: HTTP_PORT
            value: "1080"
          - name: HTTPS_PORT
            value: "10443"
          ports:
            - containerPort: 8080
            - containerPort: 10443