apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    netology: web
spec:
  containers:
  - name: web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
      - containerPort: 8080
        name: web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    netology: web
  ports:
  - name: port
    protocol: TCP
    port: 8080
    targetPort: web-svc