---
- hosts: localhost
  collections:
    - my_own_namespace.yandex_cloud_elk

  tasks:
    - import_role:
        name: my_role
    
    - my_own_module:
        path: /home/Timur/qwe.txt
        content: rty
